server:
  port: 18084

spring:
  application:
    name: rookie-nacos-config
  cloud:
    nacos:
      config:
        serverAddr: 101.43.142.12:8848
        username: 'nacos'
        password: 'nacos_123'
  config:
    import:
#      - optional:nacos:nacos-config-example.properties?refreshEnabled=true
      - nacos:nacos-config-example.properties?refreshEnabled=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#logging:
#  level:
#    com.alibaba.cloud.nacos.configdata: debug
