server:
  port: 18081
spring:
  application:
    name: rookie-feign-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.142.12:8848
        enabled: true
        namespace: rookie-cloud
      username: nacos
      password: nacos_123
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true

management:
  endpoint:
    web:
      exposure:
        include: '*'
#    health:
#      show-details: always

