server:
  port: 18086

spring:
  application:
    name: service-gateway-provider
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.142.12:8848
      username: nacos
      password: nacos_123
management:
  endpoints:
    web:
      exposure:
        include: '*'

